### PR TITLE
Add optional deinterleaving to PolarSCLDecoder so that 5G downstream signals can be decoded

### PR DESCRIPTION
**Pull request by catkira**
## Description
This PR solves this issue: https://github.com/NVlabs/sionna/issues/77 

Until now it is not possible to decode 5G downstream signals, because deinterleaving according to TS 38.212 Table 5.3.1.1 (I_IL) is not implemented. This PR implements:

- optional deinterleaving (I_IL) in PolarSCLDecoder and PolarEncoder and Polar5GEncoder
- optional channel interleaving (B_IL) in Polar5GDecoder and Polar5GEncoder (it was implemented before, but always on)
- optional specification of CRC polynomial to Polar5GEncoder (deducing CRC polynomial from payload length doesnt always work)
- make payload incl CRC available as attribute in Polar5GDecoder (so that the receiver can tell if the CRC matched)

This PR is still WIP, but I already open it for discussion. All changes preserve the old API and should not affect existing use cases.

Decoding of 5G PBCH signal with deinterleaving works (the checksum inside the SCL decoder becomes True)
The example with real 5G data can be found here:
https://github.com/catkira/py3gpp/blob/master/examples/test_py3gpp.ipynb

I will squash all commits in this PR when its done.

## Checklist

[x] Detailed description
[x] Added references to issues and discussions
[ ] Added / modified documentation as needed
[x] Added / modified unit tests as needed
[ ] Passes all tests
[x] Lint the code
[ ] Performed a self review
[ ] Ensure you Signed-off the commits. Required to accept contributions!
[x] Co-authored with someone? Add Co-authored-by: user@domain and ensure they signed off their commits too.

### CODE REVIEW

**Comment by catkira** [comment]
I noticed that 2 tests in test_mimo_ofdm_cdl.py fail. But it does not use any polar coding, very strange, maybe it happens only on my system...

**Comment by SebastianCa** [comment]
> I noticed that 2 tests in test_mimo_ofdm_cdl.py fail. But it does not use any polar coding, very strange, maybe it happens only on my system...
> 
> Edit: I opened [this](https://github.com/NVlabs/sionna/issues/85) issue about the failing test, because it does not seem to be related to this PR

Indeed, this sounds unrelated to this PR. Please ensure that you have enough GPU memory available in your system.

**Comment by catkira** [comment]
I run everyrhing in WSL, so I dont have a GPU available at the moment.

**Comment by SebastianCa** [comment]
First of all, thank you for initiating this PR. Polar downlink is certainly an important feature for the FEC module.

Just to give you a short update: we review the code in the next days and provide detailed feedback.

**Comment by catkira** [comment]
> > I noticed that 2 tests in test_mimo_ofdm_cdl.py fail. But it does not use any polar coding, very strange, maybe it happens only on my system...
> > Edit: I opened [this](https://github.com/NVlabs/sionna/issues/85) issue about the failing test, because it does not seem to be related to this PR
> 
> Indeed, this sounds unrelated to this PR. Please ensure that you have enough GPU memory available in your system.

this is resolved now, it was probably an issue with my WSL system.

**Comment by catkira** [comment]
nice, some action here again 💯

**Comment by catkira** [comment]
what else is there left to do?

**Comment by catkira** [comment]
@SebastianCa: your changes caused test_fec_5G.py to fail. Can You make sure tests pass when You make changes? (or modify the tests accordingly)

**Comment by SebastianCa** [comment]
We have reviewed the PR again and updated the API documentation accordingly.
From our side, we are ready to merge the PR - well done!

@catkira: please double-check the changes.


## Changes
- Updated docstrings
- Updated Fig. 3 PolarEncoder
- Added downlink support for SC & BP decoding in the Polar5GDecoder
- Updated testcases for downlink scenario
- Removed `iil flag`, as this is redundant with providing `ind_iil`
- Removed `u_hat_crc` attribute as it causes potential issues in Graph/XLA mode

## Remarks
- The interleaver is only defined for k<=164, this is now catched by an assertion
- The implementation ignores some tiny details about the CRC encoding in the downlink scenario (scrambling with the RNTI & all-one initialization of the CRC encoder). However, for simplicity this is acceptable and has most likely only little impact from a link-level perspective.

**Comment by catkira** [comment]
looks good, thanks for the review!

**Review by gmarcusm — DISMISSED** [review]
reviewed by Sebastian, approved.

**Comment by catkira** [comment]
> @catkira please add a Sign-off to the pull request. It is fine if you add it to the PR, I will then incorporate it into the merged commit.

I did it. You can remove the inserted space in the merge commit.

**Comment by gmarcusm** [comment]
ok, I think I was not clear, apologies. You signed the commit with a verified GPG key (thanks!). What I meant is to add:

Signed-off-by: Name <email>

as described in [CONTRIBUTING](https://github.com/NVlabs/sionna/blob/main/CONTRIBUTING.md) . This is required to "sign off" that you agree with the conditions for contributing to the project.

**Comment by catkira** [comment]
> ok, I think I was not clear, apologies. You signed the commit with a verified GPG key (thanks!). What I meant is to add:
> 
> Signed-off-by: Name
> 
> as described in [CONTRIBUTING](https://github.com/NVlabs/sionna/blob/main/CONTRIBUTING.md) . This is required to "sign off" that you agree with the conditions for contributing to the project.

ok, it's done.

**Review by gmarcusm — APPROVED** [review]

**Pull request merged**
